import React, { useState } from 'react';
import ReactDOM from 'react-dom/client';
import { EventsTable } from './components/EventsTable';
import { AttackMatrix } from './components/AttackMatrix';
import { SummaryHeader } from './components/SummaryHeader';
import { AlertsTable } from './components/AlertsTable';
import { AlertRulesManager } from './components/AlertRulesManager';
import type { EventFilters } from './api/events';

type TabId = 'events' | 'attack' | 'alerts';

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<TabId>('events');
  const [filters, setFilters] = useState<EventFilters>({});

  return (
    <div
      style={{
        minHeight: '100vh',
        backgroundColor: '#020617',
        color: '#e5e7eb',
        fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      }}
    >
      <header
        style={{
          borderBottom: '1px solid #111827',
          padding: '12px 24px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: 'radial-gradient(circle at top left, #0f172a, #020617)',
        }}
      >
        <div>
          <div style={{ fontSize: 18, fontWeight: 600 }}>Cybersecurity Monitoring</div>
          <div style={{ fontSize: 12, color: '#9ca3af' }}>Prototype dashboard</div>
        </div>
        <div style={{ fontSize: 12, color: '#6b7280' }}>Backend: /api/events &middot; Frontend: React + Vite</div>
      </header>

      <main style={{ padding: '16px 24px', maxWidth: 1200, margin: '0 auto' }}>
        <div
          style={{
            display: 'inline-flex',
            padding: '4px',
            borderRadius: '999px',
            backgroundColor: '#020617',
            border: '1px solid #1f2937',
            marginBottom: '16px',
          }}
        >
          <button
            type="button"
            onClick={() => setActiveTab('events')}
            style={{
              border: 'none',
              cursor: 'pointer',
              padding: '6px 14px',
              borderRadius: '999px',
              fontSize: 13,
              backgroundColor: activeTab === 'events' ? '#0f172a' : 'transparent',
              color: activeTab === 'events' ? '#e5e7eb' : '#9ca3af',
            }}
          >
            Events
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('attack')}
            style={{
              border: 'none',
              cursor: 'pointer',
              padding: '6px 14px',
              borderRadius: '999px',
              fontSize: 13,
              backgroundColor: activeTab === 'attack' ? '#0f172a' : 'transparent',
              color: activeTab === 'attack' ? '#e5e7eb' : '#9ca3af',
            }}
          >
            ATT&CK Matrix
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('alerts')}
            style={{
              border: 'none',
              cursor: 'pointer',
              padding: '6px 14px',
              borderRadius: '999px',
              fontSize: 13,
              backgroundColor: activeTab === 'alerts' ? '#0f172a' : 'transparent',
              color: activeTab === 'alerts' ? '#e5e7eb' : '#9ca3af',
            }}
          >
            Alerts
          </button>
        </div>

        <section style={{ marginTop: 4 }}>
          {activeTab === 'events' && (
            <>
              <h2 style={{ fontSize: 16, marginBottom: 8 }}>Security Events</h2>
              <p style={{ fontSize: 13, color: '#9ca3af', marginBottom: 12 }}>
                Live view of security events from the backend with basic filtering by severity, category and source.
              </p>
              <SummaryHeader filters={filters} />
              <EventsTable />
            </>
          )}

          {activeTab === 'attack' && (
            <>
              <h2 style={{ fontSize: 16, marginBottom: 8 }}>ATT&CK Matrix (simplified)</h2>
              <p style={{ fontSize: 13, color: '#9ca3af', marginBottom: 12 }}>
                High-level overview of tactics and techniques mapped in a simplified ATT&CK-style matrix.
              </p>
              <AttackMatrix />
            </>
          )}

          {activeTab === 'alerts' && (
            <>
              <h2 style={{ fontSize: 16, marginBottom: 8 }}>Security Alerts</h2>
              <p style={{ fontSize: 13, color: '#9ca3af', marginBottom: 12 }}>
                Alerts generated by alert rules when events match specific criteria. Manage rules and update alert status.
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
                <div>
                  <h3 style={{ fontSize: 14, marginBottom: 12 }}>Active Alerts</h3>
                  <AlertsTable />
                </div>
                <div>
                  <h3 style={{ fontSize: 14, marginBottom: 12 }}>Alert Rules</h3>
                  <AlertRulesManager />
                </div>
              </div>
            </>
          )}
        </section>
      </main>
    </div>
  );
};

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(<App />);

